version: "3"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quickstart-spring
    command: mysqld --sql_mode=""  #disable strict mode(needed since mysql 5.7.40 for use group by non aggregated columns)
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "--password=root" ]
      timeout: 0.5s
      retries: 5
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LISTENERS: "INTERNAL://:9092,EXTERNAL://:29092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9092,EXTERNAL://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      TOPICS: |
        tp_todos
    volumes:
      - ./.docker/kafka/data:/var/lib/kafka/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    command:
      - /bin/sh
      - -c
      - |
        (echo 'Waiting for Kafka to be ready...'
        cub kafka-ready -b kafka:9092 1 30
        for topic in $$TOPICS;
        do
          echo "Creating $$topic..."
          kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic $$topic
        done;)&
        /etc/confluent/docker/run

  akhq:
    image: tchiotludo/akhq:dev
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "kafka:9092"
          topic-data:
            sort: NEWEST
    ports:
      - 8000:8080
    depends_on:
      - kafka
      - zookeeper
